main: fr.azrotho.druhc.Main
version: 1.0
name: DanganronpaUHC
commands:
  start:
    description: Permet de lancer la partie
    usage: ~~Je suis un Message Inutile~~
  dr:
    description: Permet d'utiliser les Pouvoirs!
    usage: ~~Je suis un Message Inutile~~